runtime: nodejs
env: flex
env_variables:
  SQL_USER: "Akleg"
  SQL_PASSWORD: "alan123456"
  SQL_DATABASE: "officalDb"
  INSTANCE_CONNECTION_NAME: "mixov2:asia-east2:db-mixo-v2"
beta_settings:
  cloud_sql_instances: "mixov2:asia-east2:db-mixo-v2"

manual_scaling:
  instances: 1

resources:
  cpu: .5
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /
    static_files: client/build/index.html
    upload: client/build/index.html
  - url: /
    static_dir: client/build

  